# name: deploy-auth

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'auth/**'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: cd auth && docker build -t motemedkhaled/auth .
#         env:
#           DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
#           DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#       - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

#       - run: docker push motemedkhaled/auth
name: deploy-auth
on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: 'https://index.docker.io/v1/'
          logout: true
      - name: Build and push Docker image
        run: |
          cd auth
          docker build -t motemedkhaled/auth .
          docker push motemedkhaled/auth


