# name: deploy-auth

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'auth/**'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: cd auth && docker build -t motemedkhaled/auth .
#       - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#         env:
#           DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
#           DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWOERD}}
#       - run: docker push motemedkhaled/auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t motemedkhaled/auth .
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker push motemedkhaled/auth
